### ISSUE TITLE
Boxes should be cards?

### ISSUE THREAD

**Issue by eberkund** [HackerThemes/charming-issues#40]
Seems very similar and IMO it would preferable to use the standard bootstrap components wherever possible rather than introducing new components:

https://getbootstrap.com/docs/4.0/components/card/#header-and-footer

**Comment by arechsteiner** [comment]
I've considered remodeling cards. I decided to build a new component because at the time Bootstrap 4 was in early alpha and things shifted a lot with each update. I simply didn't want every Bootstrap update to break a core component and have a bit more freedom to just build it the way I think is best without considering cross-compatibility at every turn.

**Comment by eberkund** [comment]
That makes sense, I figured that was probably the reasoning behind it since cards were added in one of the later alphas if I remember right. Bootstrap is getting closer to a stable release now and I think this might be less of an issue now.

Also, thanks for the great theme! It's making my project much better. I actually switched from another theme I bought the other day after reviewing the code for the free themes and seeing how nicely coded it was. The old theme I was using made very little use of bootstrap variables so the final CSS I got was very bloated.

**Comment by arechsteiner** [comment]
Yes you're right. I might decide differently for a new template. With Charming, I think it would be a lot of duplicated effort to switch over and break things for people already using the template. I'd rather focus on adding some more features.

Also thanks for the praise. That's really good to hear!
